services:
  app:
    build: .
    ports:
      - "8004:8000"
    environment:
      - API_KEY=your-secret-api-key
      - DEFAULT_PROJECT_ID=default
      - DATA_DIR=/app/data
    restart: unless-stopped